// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: GaugeAndChartDesign

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Horizontal_Separators;
extern lv_obj_t * ui_Horizontal_Separators1;
extern lv_obj_t * ui_Horizontal_Separators2;
extern lv_obj_t * ui_Horizontal_Separators3;
extern lv_obj_t * ui_Horizontal_Separators4;
extern lv_obj_t * ui_Horizontal_Separators5;
extern lv_obj_t * ui_Horizontal_Separators6;
extern lv_obj_t * ui_Vertival_Separators;
extern lv_obj_t * ui_Vertival_Separators1;
extern lv_obj_t * ui_Vertival_Separators2;
extern lv_obj_t * ui_Vertival_Separators3;
extern lv_obj_t * ui_MainPanel;
extern lv_obj_t * ui_OIL_PRESS;
extern lv_obj_t * ui_OIL_PRESS_Label;
extern lv_obj_t * ui_OIL_PRESS_Image_1;
extern lv_obj_t * ui_OIL_PRESS_Image_2;
extern lv_obj_t * ui_OIL_PRESS_Bar;
extern lv_obj_t * ui_OIL_PRESS_CHART;
extern lv_obj_t * ui_OIL_PRESS_CHART_Xaxis;
extern lv_obj_t * ui_OIL_PRESS_CHART_Yaxis1;
extern lv_obj_t * ui_OIL_PRESS_CHART_Yaxis2;
extern lv_obj_t * ui_OIL_PRESS_Value;
extern lv_obj_t * ui_OIL_PRESS_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_OIL_TEMP;
extern lv_obj_t * ui_OIL_TEMP_Label;
extern lv_obj_t * ui_OIL_TEMP_Image_1;
extern lv_obj_t * ui_OIL_TEMP_Image_2;
extern lv_obj_t * ui_OIL_TEMP_Bar;
extern lv_obj_t * ui_OIL_TEMP_CHART;
extern lv_obj_t * ui_OIL_TEMP_CHART_Xaxis;
extern lv_obj_t * ui_OIL_TEMP_CHART_Yaxis1;
extern lv_obj_t * ui_OIL_TEMP_CHART_Yaxis2;
extern lv_obj_t * ui_OIL_TEMP_Value_P;
extern lv_obj_t * ui_OIL_TEMP_Value_C;
extern lv_obj_t * ui_OIL_TEMP_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_W_TEMP;
extern lv_obj_t * ui_W_TEMP_Label;
extern lv_obj_t * ui_W_TEMP_Image_1;
extern lv_obj_t * ui_W_TEMP_Image_2;
extern lv_obj_t * ui_W_TEMP_Bar;
extern lv_obj_t * ui_W_TEMP_CHART;
extern lv_obj_t * ui_W_TEMP_CHART_Xaxis;
extern lv_obj_t * ui_W_TEMP_CHART_Yaxis1;
extern lv_obj_t * ui_W_TEMP_CHART_Yaxis2;
extern lv_obj_t * ui_W_TEMP_Value_H;
extern lv_obj_t * ui_W_TEMP_Value_C;
extern lv_obj_t * ui_W_TEMP_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_TRAN_TEMP;
extern lv_obj_t * ui_TRAN_TEMP_Label;
extern lv_obj_t * ui_TRAN_TEMP_Image_1;
extern lv_obj_t * ui_TRAN_TEMP_Image_2;
extern lv_obj_t * ui_TRAN_TEMP_Bar;
extern lv_obj_t * ui_TRAN_TEMP_CHART;
extern lv_obj_t * ui_TRAN_TEMP_CHART_Xaxis;
extern lv_obj_t * ui_TRAN_TEMP_CHART_Yaxis1;
extern lv_obj_t * ui_TRAN_TEMP_CHART_Yaxis2;
extern lv_obj_t * ui_TRAN_TEMP_Value_H;
extern lv_obj_t * ui_TRAN_TEMP_Value_C;
extern lv_obj_t * ui_TRAN_TEMP_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_STEER_TEMP;
extern lv_obj_t * ui_STEER_TEMP_Label;
extern lv_obj_t * ui_STEER_TEMP_Image_1;
extern lv_obj_t * ui_STEER_TEMP_Image_2;
extern lv_obj_t * ui_STEER_TEMP_Bar;
extern lv_obj_t * ui_STEER_TEMP_CHART;
extern lv_obj_t * ui_STEER_TEMP_CHART_Xaxis;
extern lv_obj_t * ui_STEER_TEMP_CHART_Yaxis1;
extern lv_obj_t * ui_STEER_TEMP_CHART_Yaxis2;
extern lv_obj_t * ui_STEER_TEMP_Value_H;
extern lv_obj_t * ui_STEER_TEMP_Value_C;
extern lv_obj_t * ui_STEER_TEMP_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_DIFF_TEMP;
extern lv_obj_t * ui_DIFF_TEMP_Label;
extern lv_obj_t * ui_DIFF_TEMP_Image_1;
extern lv_obj_t * ui_DIFF_TEMP_Image_2;
extern lv_obj_t * ui_DIFF_TEMP_Bar;
extern lv_obj_t * ui_DIFF_TEMP_CHART;
extern lv_obj_t * ui_DIFF_TEMP_CHART_Xaxis;
extern lv_obj_t * ui_DIFF_TEMP_CHART_Yaxis1;
extern lv_obj_t * ui_DIFF_TEMP_CHART_Yaxis2;
extern lv_obj_t * ui_DIFF_TEMP_Value_H;
extern lv_obj_t * ui_DIFF_TEMP_Value_C;
extern lv_obj_t * ui_DIFF_TEMP_VALUE_CRITICAL_Label;
extern lv_obj_t * ui_FUEL_TRUST;
extern lv_obj_t * ui_FUEL_TRUST_Label;
extern lv_obj_t * ui_FUEL_TRUST_Image;
extern lv_obj_t * ui_FUEL_TRUST_Bar;
extern lv_obj_t * ui_FUEL_TRUST_CHART;
extern lv_obj_t * ui_FUEL_TRUST_CHART_Xaxis;
extern lv_obj_t * ui_FUEL_TRUST_CHART_Yaxis1;
extern lv_obj_t * ui_FUEL_TRUST_CHART_Yaxis2;
extern lv_obj_t * ui_FUEL_TRUST_Value;
extern lv_obj_t * ui_FUEL_TRUST_VALUE_CRITICAL_Label;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

