// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: GaugeAndChartDesign

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    
    // Initialize both screens
    ui_ScreenSplash_screen_init();  // Splash screen (loaded first)
    ui_Screen1_screen_init();        // Main screen (loaded after splash)
    
    ui____initial_actions0 = lv_obj_create(NULL);
    
    // Load splash screen first - it will auto-transition to Screen1
    lv_disp_load_scr(ui_ScreenSplash);
}

void ui_destroy(void)
{
    ui_ScreenSplash_screen_destroy();
    ui_Screen1_screen_destroy();
}
