// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: GaugeAndChartDesign

#ifndef _GAUGEANDCHARTDESIGN_UI_H
#define _GAUGEANDCHARTDESIGN_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_ScreenSplash.h"
#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_788234086);    // assets/icons8-engine-oil-windows-10/icons8-engine-oil-96.png
LV_IMG_DECLARE(ui_img_111761047);    // assets/icons8-pressure-windows-10/icons8-pressure-64.png
LV_IMG_DECLARE(ui_img_91236053);    // assets/icons8-temperature-windows-10/icons8-temperature-64.png
LV_IMG_DECLARE(ui_img_1610037518);    // assets/icons8-wave-lines-windows-10/icons8-wave-lines-96.png
LV_IMG_DECLARE(ui_img_1101422646);    // assets/icons8-gear-windows-11-outline/icons8-gear-96.png
LV_IMG_DECLARE(ui_img_837429808);    // assets/icons8-steering-wheel-windows-11-filled/icons8-steering-wheel-96.png
LV_IMG_DECLARE(ui_img_260142572);    // assets/icons8-differential/icons8-differential-96.png
LV_IMG_DECLARE(ui_img_2038433484);    // assets/icons8-petrol-windows-10/icons8-petrol-96.png

// FONTS
LV_FONT_DECLARE(ui_font_OrbitronExtraBold12);
LV_FONT_DECLARE(ui_font_OrbitronExtraBold18);
LV_FONT_DECLARE(ui_font_OrbitronExtraBold26);
LV_FONT_DECLARE(ui_font_OrbitronExtraBold34);
LV_FONT_DECLARE(ui_font_OrbitronExtraBold42);
LV_FONT_DECLARE(ui_font_OrbitronExtraBold48);
LV_FONT_DECLARE(ui_font_OrbitronMedium12);
LV_FONT_DECLARE(ui_font_OrbitronMedium18);
LV_FONT_DECLARE(ui_font_OrbitronMedium24);
LV_FONT_DECLARE(ui_font_OrbitronMedium26);
LV_FONT_DECLARE(ui_font_OrbitronMedium34);
LV_FONT_DECLARE(ui_font_OrbitronMedium42);
LV_FONT_DECLARE(ui_font_OrbitronMedium48);
LV_FONT_DECLARE(ui_font_OrbitronMedium8);
LV_FONT_DECLARE(ui_font_OrbitronRegular12);
LV_FONT_DECLARE(ui_font_OrbitronRegular18);
LV_FONT_DECLARE(ui_font_OrbitronRegular26);
LV_FONT_DECLARE(ui_font_OrbitronRegular34);
LV_FONT_DECLARE(ui_font_OrbitronRegular42);
LV_FONT_DECLARE(ui_font_OrbitronRegular48);
LV_FONT_DECLARE(ui_font_OrbitronRegular8);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold12);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold18);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold26);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold34);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold42);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold48);
LV_FONT_DECLARE(ui_font_OrbitronSemiBold8);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght12);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght18);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght26);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght34);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght42);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght48);
LV_FONT_DECLARE(ui_font_OrbitronVariableFontwght8);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
