// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: GaugeAndChartDesign

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Horizontal_Separators = NULL;
lv_obj_t * ui_Horizontal_Separators1 = NULL;
lv_obj_t * ui_Horizontal_Separators2 = NULL;
lv_obj_t * ui_Horizontal_Separators3 = NULL;
lv_obj_t * ui_Horizontal_Separators4 = NULL;
lv_obj_t * ui_Horizontal_Separators5 = NULL;
lv_obj_t * ui_Horizontal_Separators6 = NULL;
lv_obj_t * ui_Vertival_Separators = NULL;
lv_obj_t * ui_Vertival_Separators1 = NULL;
lv_obj_t * ui_Vertival_Separators2 = NULL;
lv_obj_t * ui_Vertival_Separators3 = NULL;
lv_obj_t * ui_MainPanel = NULL;
lv_obj_t * ui_OIL_PRESS = NULL;
lv_obj_t * ui_OIL_PRESS_Label = NULL;
lv_obj_t * ui_OIL_PRESS_Image_1 = NULL;
lv_obj_t * ui_OIL_PRESS_Image_2 = NULL;
lv_obj_t * ui_OIL_PRESS_Bar = NULL;
lv_obj_t * ui_OIL_PRESS_CHART = NULL;
lv_obj_t * ui_OIL_PRESS_CHART_Xaxis = NULL;
lv_obj_t * ui_OIL_PRESS_CHART_Yaxis1 = NULL;
lv_obj_t * ui_OIL_PRESS_CHART_Yaxis2 = NULL;
lv_obj_t * ui_OIL_PRESS_Value = NULL;
lv_obj_t * ui_OIL_PRESS_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_OIL_TEMP = NULL;
lv_obj_t * ui_OIL_TEMP_Label = NULL;
lv_obj_t * ui_OIL_TEMP_Image_1 = NULL;
lv_obj_t * ui_OIL_TEMP_Image_2 = NULL;
lv_obj_t * ui_OIL_TEMP_Bar = NULL;
lv_obj_t * ui_OIL_TEMP_CHART = NULL;
lv_obj_t * ui_OIL_TEMP_CHART_Xaxis = NULL;
lv_obj_t * ui_OIL_TEMP_CHART_Yaxis1 = NULL;
lv_obj_t * ui_OIL_TEMP_CHART_Yaxis2 = NULL;
lv_obj_t * ui_OIL_TEMP_Value_P = NULL;
lv_obj_t * ui_OIL_TEMP_Value_C = NULL;
lv_obj_t * ui_OIL_TEMP_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_W_TEMP = NULL;
lv_obj_t * ui_W_TEMP_Label = NULL;
lv_obj_t * ui_W_TEMP_Image_1 = NULL;
lv_obj_t * ui_W_TEMP_Image_2 = NULL;
lv_obj_t * ui_W_TEMP_Bar = NULL;
lv_obj_t * ui_W_TEMP_CHART = NULL;
lv_obj_t * ui_W_TEMP_CHART_Xaxis = NULL;
lv_obj_t * ui_W_TEMP_CHART_Yaxis1 = NULL;
lv_obj_t * ui_W_TEMP_CHART_Yaxis2 = NULL;
lv_obj_t * ui_W_TEMP_Value_H = NULL;
lv_obj_t * ui_W_TEMP_Value_C = NULL;
lv_obj_t * ui_W_TEMP_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_TRAN_TEMP = NULL;
lv_obj_t * ui_TRAN_TEMP_Label = NULL;
lv_obj_t * ui_TRAN_TEMP_Image_1 = NULL;
lv_obj_t * ui_TRAN_TEMP_Image_2 = NULL;
lv_obj_t * ui_TRAN_TEMP_Bar = NULL;
lv_obj_t * ui_TRAN_TEMP_CHART = NULL;
lv_obj_t * ui_TRAN_TEMP_CHART_Xaxis = NULL;
lv_obj_t * ui_TRAN_TEMP_CHART_Yaxis1 = NULL;
lv_obj_t * ui_TRAN_TEMP_CHART_Yaxis2 = NULL;
lv_obj_t * ui_TRAN_TEMP_Value_H = NULL;
lv_obj_t * ui_TRAN_TEMP_Value_C = NULL;
lv_obj_t * ui_TRAN_TEMP_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_STEER_TEMP = NULL;
lv_obj_t * ui_STEER_TEMP_Label = NULL;
lv_obj_t * ui_STEER_TEMP_Image_1 = NULL;
lv_obj_t * ui_STEER_TEMP_Image_2 = NULL;
lv_obj_t * ui_STEER_TEMP_Bar = NULL;
lv_obj_t * ui_STEER_TEMP_CHART = NULL;
lv_obj_t * ui_STEER_TEMP_CHART_Xaxis = NULL;
lv_obj_t * ui_STEER_TEMP_CHART_Yaxis1 = NULL;
lv_obj_t * ui_STEER_TEMP_CHART_Yaxis2 = NULL;
lv_obj_t * ui_STEER_TEMP_Value_H = NULL;
lv_obj_t * ui_STEER_TEMP_Value_C = NULL;
lv_obj_t * ui_STEER_TEMP_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_DIFF_TEMP = NULL;
lv_obj_t * ui_DIFF_TEMP_Label = NULL;
lv_obj_t * ui_DIFF_TEMP_Image_1 = NULL;
lv_obj_t * ui_DIFF_TEMP_Image_2 = NULL;
lv_obj_t * ui_DIFF_TEMP_Bar = NULL;
lv_obj_t * ui_DIFF_TEMP_CHART = NULL;
lv_obj_t * ui_DIFF_TEMP_CHART_Xaxis = NULL;
lv_obj_t * ui_DIFF_TEMP_CHART_Yaxis1 = NULL;
lv_obj_t * ui_DIFF_TEMP_CHART_Yaxis2 = NULL;
lv_obj_t * ui_DIFF_TEMP_Value_H = NULL;
lv_obj_t * ui_DIFF_TEMP_Value_C = NULL;
lv_obj_t * ui_DIFF_TEMP_VALUE_CRITICAL_Label = NULL;
lv_obj_t * ui_FUEL_TRUST = NULL;
lv_obj_t * ui_FUEL_TRUST_Label = NULL;
lv_obj_t * ui_FUEL_TRUST_Image = NULL;
lv_obj_t * ui_FUEL_TRUST_Bar = NULL;
lv_obj_t * ui_FUEL_TRUST_CHART = NULL;
lv_obj_t * ui_FUEL_TRUST_CHART_Xaxis = NULL;
lv_obj_t * ui_FUEL_TRUST_CHART_Yaxis1 = NULL;
lv_obj_t * ui_FUEL_TRUST_CHART_Yaxis2 = NULL;
lv_obj_t * ui_FUEL_TRUST_Value = NULL;
lv_obj_t * ui_FUEL_TRUST_VALUE_CRITICAL_Label = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Horizontal_Separators);
    lv_obj_set_width(ui_Horizontal_Separators, lv_pct(100));
    lv_obj_set_height(ui_Horizontal_Separators, lv_pct(100));
    lv_obj_set_align(ui_Horizontal_Separators, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators1 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators1, 2);
    lv_obj_set_width(ui_Horizontal_Separators1, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators1, 0);
    lv_obj_set_y(ui_Horizontal_Separators1, 68);
    lv_obj_set_align(ui_Horizontal_Separators1, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators2 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators2, 2);
    lv_obj_set_width(ui_Horizontal_Separators2, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators2, 0);
    lv_obj_set_y(ui_Horizontal_Separators2, 136);
    lv_obj_set_align(ui_Horizontal_Separators2, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators3 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators3, 2);
    lv_obj_set_width(ui_Horizontal_Separators3, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators3, 0);
    lv_obj_set_y(ui_Horizontal_Separators3, 204);
    lv_obj_set_align(ui_Horizontal_Separators3, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators4 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators4, 2);
    lv_obj_set_width(ui_Horizontal_Separators4, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators4, 0);
    lv_obj_set_y(ui_Horizontal_Separators4, 272);
    lv_obj_set_align(ui_Horizontal_Separators4, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators5 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators5, 2);
    lv_obj_set_width(ui_Horizontal_Separators5, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators5, 0);
    lv_obj_set_y(ui_Horizontal_Separators5, 340);
    lv_obj_set_align(ui_Horizontal_Separators5, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Horizontal_Separators6 = lv_obj_create(ui_Horizontal_Separators);
    lv_obj_set_height(ui_Horizontal_Separators6, 2);
    lv_obj_set_width(ui_Horizontal_Separators6, lv_pct(100));
    lv_obj_set_x(ui_Horizontal_Separators6, 0);
    lv_obj_set_y(ui_Horizontal_Separators6, 408);
    lv_obj_set_align(ui_Horizontal_Separators6, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_Horizontal_Separators6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Vertival_Separators = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_Vertival_Separators);
    lv_obj_set_width(ui_Vertival_Separators, lv_pct(100));
    lv_obj_set_height(ui_Vertival_Separators, lv_pct(100));
    lv_obj_set_align(ui_Vertival_Separators, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Vertival_Separators, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Vertival_Separators1 = lv_obj_create(ui_Vertival_Separators);
    lv_obj_set_width(ui_Vertival_Separators1, 2);
    lv_obj_set_height(ui_Vertival_Separators1, lv_pct(100));
    lv_obj_set_x(ui_Vertival_Separators1, -170);
    lv_obj_set_y(ui_Vertival_Separators1, lv_pct(0));
    lv_obj_set_align(ui_Vertival_Separators1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Vertival_Separators1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Vertival_Separators2 = lv_obj_create(ui_Vertival_Separators);
    lv_obj_set_width(ui_Vertival_Separators2, 2);
    lv_obj_set_height(ui_Vertival_Separators2, lv_pct(100));
    lv_obj_set_x(ui_Vertival_Separators2, -89);
    lv_obj_set_y(ui_Vertival_Separators2, lv_pct(0));
    lv_obj_set_align(ui_Vertival_Separators2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Vertival_Separators2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Vertival_Separators3 = lv_obj_create(ui_Vertival_Separators);
    lv_obj_set_width(ui_Vertival_Separators3, 2);
    lv_obj_set_height(ui_Vertival_Separators3, lv_pct(100));
    lv_obj_set_x(ui_Vertival_Separators3, 258);
    lv_obj_set_y(ui_Vertival_Separators3, lv_pct(0));
    lv_obj_set_align(ui_Vertival_Separators3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Vertival_Separators3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MainPanel = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_MainPanel, 800);
    lv_obj_set_height(ui_MainPanel, 480);
    lv_obj_set_align(ui_MainPanel, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_MainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MainPanel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainPanel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_OIL_PRESS);
    lv_obj_set_height(ui_OIL_PRESS, 68);
    lv_obj_set_width(ui_OIL_PRESS, lv_pct(105));
    lv_obj_set_x(ui_OIL_PRESS, 0);
    lv_obj_set_y(ui_OIL_PRESS, -20);
    lv_obj_set_align(ui_OIL_PRESS, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_OIL_PRESS, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OIL_PRESS_Label = lv_label_create(ui_OIL_PRESS);
    lv_obj_set_width(ui_OIL_PRESS_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_PRESS_Label, LV_SIZE_CONTENT);    /// 0
    lv_obj_set_x(ui_OIL_PRESS_Label, 9);
    lv_obj_set_y(ui_OIL_PRESS_Label, -1);
    lv_obj_set_align(ui_OIL_PRESS_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OIL_PRESS_Label, "OIL-PRESS");
    lv_obj_set_style_text_font(ui_OIL_PRESS_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS_Image_1 = lv_image_create(ui_OIL_PRESS);
    lv_image_set_src(ui_OIL_PRESS_Image_1, &ui_img_788234086);
    lv_obj_set_x(ui_OIL_PRESS_Image_1, 218);
    lv_obj_set_y(ui_OIL_PRESS_Image_1, 9);
    lv_obj_set_align(ui_OIL_PRESS_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_OIL_PRESS_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_PRESS_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_OIL_PRESS_Image_1, 150);
    lv_obj_set_style_image_recolor(ui_OIL_PRESS_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_OIL_PRESS_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS_Image_2 = lv_image_create(ui_OIL_PRESS);
    lv_image_set_src(ui_OIL_PRESS_Image_2, &ui_img_111761047);
    lv_obj_set_x(ui_OIL_PRESS_Image_2, 230);
    lv_obj_set_y(ui_OIL_PRESS_Image_2, -16);
    lv_obj_set_align(ui_OIL_PRESS_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_OIL_PRESS_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_PRESS_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_OIL_PRESS_Image_2, 105);
    lv_obj_set_style_image_recolor(ui_OIL_PRESS_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_OIL_PRESS_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS_Bar = lv_bar_create(ui_OIL_PRESS);
    lv_bar_set_range(ui_OIL_PRESS_Bar, 5, 150);
    lv_obj_set_width(ui_OIL_PRESS_Bar, 345);
    lv_obj_set_height(ui_OIL_PRESS_Bar, 66);
    lv_obj_set_x(ui_OIL_PRESS_Bar, 84);
    lv_obj_set_y(ui_OIL_PRESS_Bar, -1);
    lv_obj_set_align(ui_OIL_PRESS_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_OIL_PRESS_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OIL_PRESS_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_PRESS_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_OIL_PRESS_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OIL_PRESS_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_PRESS_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_OIL_PRESS_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_OIL_PRESS_Bar,
                                                                                                    lv_obj_get_style_pad_right(ui_OIL_PRESS_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_OIL_PRESS_CHART = lv_chart_create(ui_OIL_PRESS);
    lv_obj_set_width(ui_OIL_PRESS_CHART, 345);
    lv_obj_set_height(ui_OIL_PRESS_CHART, 68);
    lv_obj_set_x(ui_OIL_PRESS_CHART, 84);
    lv_obj_set_y(ui_OIL_PRESS_CHART, -2);
    lv_obj_set_align(ui_OIL_PRESS_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OIL_PRESS_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_PRESS_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_OIL_PRESS_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_OIL_PRESS_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_OIL_PRESS_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_OIL_PRESS_CHART, 24);
    lv_chart_set_range(ui_OIL_PRESS_CHART, LV_CHART_AXIS_PRIMARY_Y, 5, 150);
    lv_chart_set_div_line_count(ui_OIL_PRESS_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_OIL_PRESS_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OIL_PRESS_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_OIL_PRESS_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OIL_PRESS_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS_CHART_Xaxis = lv_scale_create(ui_OIL_PRESS_CHART);
    lv_scale_set_mode(ui_OIL_PRESS_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_OIL_PRESS_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_OIL_PRESS_CHART_Xaxis, false);
    ui_OIL_PRESS_CHART_Yaxis1 = lv_scale_create(ui_OIL_PRESS_CHART);
    lv_scale_set_mode(ui_OIL_PRESS_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_OIL_PRESS_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_OIL_PRESS_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_OIL_PRESS_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_OIL_PRESS_CHART_Yaxis1,  5, 150);
    lv_scale_set_total_tick_count(ui_OIL_PRESS_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_OIL_PRESS_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_OIL_PRESS_CHART_Yaxis1, false);
    ui_OIL_PRESS_CHART_Yaxis2 = lv_scale_create(ui_OIL_PRESS_CHART);
    lv_scale_set_mode(ui_OIL_PRESS_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_OIL_PRESS_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_OIL_PRESS_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_OIL_PRESS_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_OIL_PRESS_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_OIL_PRESS_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_OIL_PRESS_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_OIL_PRESS_CHART_Yaxis2, false);
    lv_chart_series_t * ui_OIL_PRESS_CHART_series_1 = lv_chart_add_series(ui_OIL_PRESS_CHART, lv_color_hex(0xEA871E),
                                                                          LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_OIL_PRESS_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_OIL_PRESS_CHART, ui_OIL_PRESS_CHART_series_1, ui_OIL_PRESS_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_OIL_PRESS_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_OIL_PRESS_Value = lv_label_create(ui_OIL_PRESS);
    lv_obj_set_width(ui_OIL_PRESS_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_PRESS_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_PRESS_Value, -4);
    lv_obj_set_y(ui_OIL_PRESS_Value, -1);
    lv_obj_set_align(ui_OIL_PRESS_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_OIL_PRESS_Value, "0 PSI");
    lv_obj_set_style_text_font(ui_OIL_PRESS_Value, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_PRESS_VALUE_CRITICAL_Label = lv_label_create(ui_OIL_PRESS);
    lv_obj_set_width(ui_OIL_PRESS_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_PRESS_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_PRESS_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_OIL_PRESS_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_OIL_PRESS_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OIL_PRESS_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_OIL_PRESS_VALUE_CRITICAL_Label, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OIL_PRESS_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_OIL_PRESS_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OIL_PRESS_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_OIL_TEMP);
    lv_obj_set_height(ui_OIL_TEMP, 68);
    lv_obj_set_width(ui_OIL_TEMP, lv_pct(105));
    lv_obj_set_x(ui_OIL_TEMP, 0);
    lv_obj_set_y(ui_OIL_TEMP, 48);
    lv_obj_set_align(ui_OIL_TEMP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_OIL_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_OIL_TEMP_Label = lv_label_create(ui_OIL_TEMP);
    lv_obj_set_width(ui_OIL_TEMP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_TEMP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_TEMP_Label, 9);
    lv_obj_set_y(ui_OIL_TEMP_Label, 0);
    lv_obj_set_align(ui_OIL_TEMP_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OIL_TEMP_Label, "OIL-TEMP");
    lv_obj_set_style_text_font(ui_OIL_TEMP_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_Image_1 = lv_image_create(ui_OIL_TEMP);
    lv_image_set_src(ui_OIL_TEMP_Image_1, &ui_img_788234086);
    lv_obj_set_width(ui_OIL_TEMP_Image_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_TEMP_Image_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_TEMP_Image_1, 218);
    lv_obj_set_y(ui_OIL_TEMP_Image_1, 9);
    lv_obj_set_align(ui_OIL_TEMP_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_OIL_TEMP_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_TEMP_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_OIL_TEMP_Image_1, 150);
    lv_obj_set_style_image_recolor(ui_OIL_TEMP_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_OIL_TEMP_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_Image_2 = lv_image_create(ui_OIL_TEMP);
    lv_image_set_src(ui_OIL_TEMP_Image_2, &ui_img_91236053);
    lv_obj_set_x(ui_OIL_TEMP_Image_2, 230);
    lv_obj_set_y(ui_OIL_TEMP_Image_2, -16);
    lv_obj_set_align(ui_OIL_TEMP_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_OIL_TEMP_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_TEMP_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_OIL_TEMP_Image_2, 125);
    lv_obj_set_style_image_recolor(ui_OIL_TEMP_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_OIL_TEMP_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_Bar = lv_bar_create(ui_OIL_TEMP);
    lv_bar_set_range(ui_OIL_TEMP_Bar, 150, 300);
    lv_obj_set_width(ui_OIL_TEMP_Bar, 345);
    lv_obj_set_height(ui_OIL_TEMP_Bar, 66);
    lv_obj_set_x(ui_OIL_TEMP_Bar, 84);
    lv_obj_set_y(ui_OIL_TEMP_Bar, -1);
    lv_obj_set_align(ui_OIL_TEMP_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_OIL_TEMP_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OIL_TEMP_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_TEMP_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_OIL_TEMP_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_OIL_TEMP_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_TEMP_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_OIL_TEMP_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_OIL_TEMP_Bar,
                                                                                                   lv_obj_get_style_pad_right(ui_OIL_TEMP_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_OIL_TEMP_CHART = lv_chart_create(ui_OIL_TEMP);
    lv_obj_set_width(ui_OIL_TEMP_CHART, 345);
    lv_obj_set_height(ui_OIL_TEMP_CHART, 68);
    lv_obj_set_x(ui_OIL_TEMP_CHART, 84);
    lv_obj_set_y(ui_OIL_TEMP_CHART, -2);
    lv_obj_set_align(ui_OIL_TEMP_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OIL_TEMP_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_OIL_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_OIL_TEMP_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_OIL_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_OIL_TEMP_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_OIL_TEMP_CHART, 24);
    lv_chart_set_range(ui_OIL_TEMP_CHART, LV_CHART_AXIS_PRIMARY_Y, 150, 300);
    lv_chart_set_div_line_count(ui_OIL_TEMP_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_OIL_TEMP_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OIL_TEMP_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_OIL_TEMP_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_OIL_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_CHART_Xaxis = lv_scale_create(ui_OIL_TEMP_CHART);
    lv_scale_set_mode(ui_OIL_TEMP_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_OIL_TEMP_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_OIL_TEMP_CHART_Xaxis, false);
    ui_OIL_TEMP_CHART_Yaxis1 = lv_scale_create(ui_OIL_TEMP_CHART);
    lv_scale_set_mode(ui_OIL_TEMP_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_OIL_TEMP_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_OIL_TEMP_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_OIL_TEMP_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_OIL_TEMP_CHART_Yaxis1,  150, 300);
    lv_scale_set_total_tick_count(ui_OIL_TEMP_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_OIL_TEMP_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_OIL_TEMP_CHART_Yaxis1, false);
    ui_OIL_TEMP_CHART_Yaxis2 = lv_scale_create(ui_OIL_TEMP_CHART);
    lv_scale_set_mode(ui_OIL_TEMP_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_OIL_TEMP_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_OIL_TEMP_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_OIL_TEMP_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_OIL_TEMP_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_OIL_TEMP_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_OIL_TEMP_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_OIL_TEMP_CHART_Yaxis2, false);
    lv_chart_series_t * ui_OIL_TEMP_CHART_series_1 = lv_chart_add_series(ui_OIL_TEMP_CHART, lv_color_hex(0xEA871E),
                                                                         LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_OIL_TEMP_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_OIL_TEMP_CHART, ui_OIL_TEMP_CHART_series_1, ui_OIL_TEMP_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_OIL_TEMP_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_OIL_TEMP_Value_P = lv_label_create(ui_OIL_TEMP);
    lv_obj_set_width(ui_OIL_TEMP_Value_P, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_TEMP_Value_P, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_TEMP_Value_P, -4);
    lv_obj_set_y(ui_OIL_TEMP_Value_P, -15);
    lv_obj_set_align(ui_OIL_TEMP_Value_P, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_OIL_TEMP_Value_P, "0°F [P]");
    lv_obj_set_style_text_font(ui_OIL_TEMP_Value_P, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_Value_C = lv_label_create(ui_OIL_TEMP);
    lv_obj_set_width(ui_OIL_TEMP_Value_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_TEMP_Value_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_TEMP_Value_C, -4);
    lv_obj_set_y(ui_OIL_TEMP_Value_C, 14);
    lv_obj_set_align(ui_OIL_TEMP_Value_C, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_OIL_TEMP_Value_C, "0°F [C]");
    lv_obj_set_style_text_font(ui_OIL_TEMP_Value_C, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OIL_TEMP_VALUE_CRITICAL_Label = lv_label_create(ui_OIL_TEMP);
    lv_obj_set_width(ui_OIL_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OIL_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OIL_TEMP_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_OIL_TEMP_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_OIL_TEMP_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_OIL_TEMP_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_OIL_TEMP_VALUE_CRITICAL_Label, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OIL_TEMP_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_OIL_TEMP_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OIL_TEMP_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_W_TEMP);
    lv_obj_set_height(ui_W_TEMP, 68);
    lv_obj_set_width(ui_W_TEMP, lv_pct(105));
    lv_obj_set_x(ui_W_TEMP, 0);
    lv_obj_set_y(ui_W_TEMP, 116);
    lv_obj_set_align(ui_W_TEMP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_W_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_W_TEMP_Label = lv_label_create(ui_W_TEMP);
    lv_obj_set_width(ui_W_TEMP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_Label, 9);
    lv_obj_set_y(ui_W_TEMP_Label, 0);
    lv_obj_set_align(ui_W_TEMP_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_W_TEMP_Label, "W-TEMP");
    lv_obj_set_style_text_font(ui_W_TEMP_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_Image_1 = lv_image_create(ui_W_TEMP);
    lv_image_set_src(ui_W_TEMP_Image_1, &ui_img_1610037518);
    lv_obj_set_width(ui_W_TEMP_Image_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_Image_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_Image_1, 218);
    lv_obj_set_y(ui_W_TEMP_Image_1, 11);
    lv_obj_set_align(ui_W_TEMP_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_W_TEMP_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_W_TEMP_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_W_TEMP_Image_1, 150);
    lv_obj_set_style_image_recolor(ui_W_TEMP_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_W_TEMP_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_Image_2 = lv_image_create(ui_W_TEMP);
    lv_image_set_src(ui_W_TEMP_Image_2, &ui_img_91236053);
    lv_obj_set_width(ui_W_TEMP_Image_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_Image_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_Image_2, 233);
    lv_obj_set_y(ui_W_TEMP_Image_2, -16);
    lv_obj_set_align(ui_W_TEMP_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_W_TEMP_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_W_TEMP_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_W_TEMP_Image_2, 125);
    lv_obj_set_style_image_recolor(ui_W_TEMP_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_W_TEMP_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_Bar = lv_bar_create(ui_W_TEMP);
    lv_bar_set_range(ui_W_TEMP_Bar, 100, 260);
    lv_obj_set_width(ui_W_TEMP_Bar, 345);
    lv_obj_set_height(ui_W_TEMP_Bar, 66);
    lv_obj_set_x(ui_W_TEMP_Bar, 84);
    lv_obj_set_y(ui_W_TEMP_Bar, -1);
    lv_obj_set_align(ui_W_TEMP_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_W_TEMP_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_W_TEMP_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_W_TEMP_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_W_TEMP_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_W_TEMP_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_W_TEMP_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_W_TEMP_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_W_TEMP_Bar,
                                                                                                 lv_obj_get_style_pad_right(ui_W_TEMP_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_W_TEMP_CHART = lv_chart_create(ui_W_TEMP);
    lv_obj_set_width(ui_W_TEMP_CHART, 345);
    lv_obj_set_height(ui_W_TEMP_CHART, 68);
    lv_obj_set_x(ui_W_TEMP_CHART, 84);
    lv_obj_set_y(ui_W_TEMP_CHART, -2);
    lv_obj_set_align(ui_W_TEMP_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_W_TEMP_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_W_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_W_TEMP_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_W_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_W_TEMP_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_W_TEMP_CHART, 24);
    lv_chart_set_range(ui_W_TEMP_CHART, LV_CHART_AXIS_PRIMARY_Y, 100, 260);
    lv_chart_set_div_line_count(ui_W_TEMP_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_W_TEMP_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_W_TEMP_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_W_TEMP_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_W_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_CHART_Xaxis = lv_scale_create(ui_W_TEMP_CHART);
    lv_scale_set_mode(ui_W_TEMP_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_W_TEMP_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_W_TEMP_CHART_Xaxis, false);
    ui_W_TEMP_CHART_Yaxis1 = lv_scale_create(ui_W_TEMP_CHART);
    lv_scale_set_mode(ui_W_TEMP_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_W_TEMP_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_W_TEMP_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_W_TEMP_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_W_TEMP_CHART_Yaxis1,  100, 260);
    lv_scale_set_total_tick_count(ui_W_TEMP_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_W_TEMP_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_W_TEMP_CHART_Yaxis1, false);
    ui_W_TEMP_CHART_Yaxis2 = lv_scale_create(ui_W_TEMP_CHART);
    lv_scale_set_mode(ui_W_TEMP_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_W_TEMP_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_W_TEMP_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_W_TEMP_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_W_TEMP_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_W_TEMP_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_W_TEMP_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_W_TEMP_CHART_Yaxis2, false);
    lv_chart_series_t * ui_W_TEMP_CHART_series_1 = lv_chart_add_series(ui_W_TEMP_CHART, lv_color_hex(0xEA871E),
                                                                       LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_W_TEMP_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_W_TEMP_CHART, ui_W_TEMP_CHART_series_1, ui_W_TEMP_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_W_TEMP_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_W_TEMP_Value_H = lv_label_create(ui_W_TEMP);
    lv_obj_set_width(ui_W_TEMP_Value_H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_Value_H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_Value_H, -5);
    lv_obj_set_y(ui_W_TEMP_Value_H, -15);
    lv_obj_set_align(ui_W_TEMP_Value_H, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_W_TEMP_Value_H, "0°F [H]");
    lv_obj_set_style_text_font(ui_W_TEMP_Value_H, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_Value_C = lv_label_create(ui_W_TEMP);
    lv_obj_set_width(ui_W_TEMP_Value_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_Value_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_Value_C, -5);
    lv_obj_set_y(ui_W_TEMP_Value_C, 14);
    lv_obj_set_align(ui_W_TEMP_Value_C, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_W_TEMP_Value_C, "0°F [C]");
    lv_obj_set_style_text_font(ui_W_TEMP_Value_C, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_W_TEMP_VALUE_CRITICAL_Label = lv_label_create(ui_W_TEMP);
    lv_obj_set_width(ui_W_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_W_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_W_TEMP_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_W_TEMP_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_W_TEMP_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_W_TEMP_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_W_TEMP_VALUE_CRITICAL_Label, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_W_TEMP_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_W_TEMP_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_W_TEMP_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_TRAN_TEMP);
    lv_obj_set_height(ui_TRAN_TEMP, 68);
    lv_obj_set_width(ui_TRAN_TEMP, lv_pct(105));
    lv_obj_set_x(ui_TRAN_TEMP, 0);
    lv_obj_set_y(ui_TRAN_TEMP, 184);
    lv_obj_set_align(ui_TRAN_TEMP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_TRAN_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TRAN_TEMP_Label = lv_label_create(ui_TRAN_TEMP);
    lv_obj_set_width(ui_TRAN_TEMP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_Label, 9);
    lv_obj_set_y(ui_TRAN_TEMP_Label, 0);
    lv_obj_set_align(ui_TRAN_TEMP_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TRAN_TEMP_Label, "TRAN-TEMP");
    lv_obj_set_style_text_font(ui_TRAN_TEMP_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_Image_1 = lv_image_create(ui_TRAN_TEMP);
    lv_image_set_src(ui_TRAN_TEMP_Image_1, &ui_img_1101422646);
    lv_obj_set_width(ui_TRAN_TEMP_Image_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_Image_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_Image_1, 218);
    lv_obj_set_y(ui_TRAN_TEMP_Image_1, 12);
    lv_obj_set_align(ui_TRAN_TEMP_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_TRAN_TEMP_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TRAN_TEMP_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TRAN_TEMP_Image_1, 110);
    lv_obj_set_style_image_recolor(ui_TRAN_TEMP_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_TRAN_TEMP_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_Image_2 = lv_image_create(ui_TRAN_TEMP);
    lv_image_set_src(ui_TRAN_TEMP_Image_2, &ui_img_91236053);
    lv_obj_set_width(ui_TRAN_TEMP_Image_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_Image_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_Image_2, 234);
    lv_obj_set_y(ui_TRAN_TEMP_Image_2, -18);
    lv_obj_set_align(ui_TRAN_TEMP_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_TRAN_TEMP_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TRAN_TEMP_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_TRAN_TEMP_Image_2, 125);
    lv_obj_set_style_image_recolor(ui_TRAN_TEMP_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_TRAN_TEMP_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_Bar = lv_bar_create(ui_TRAN_TEMP);
    lv_bar_set_range(ui_TRAN_TEMP_Bar, 80, 280);
    lv_obj_set_width(ui_TRAN_TEMP_Bar, 345);
    lv_obj_set_height(ui_TRAN_TEMP_Bar, 66);
    lv_obj_set_x(ui_TRAN_TEMP_Bar, 84);
    lv_obj_set_y(ui_TRAN_TEMP_Bar, -1);
    lv_obj_set_align(ui_TRAN_TEMP_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_TRAN_TEMP_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TRAN_TEMP_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TRAN_TEMP_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_TRAN_TEMP_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TRAN_TEMP_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TRAN_TEMP_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_TRAN_TEMP_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_TRAN_TEMP_Bar,
                                                                                                    lv_obj_get_style_pad_right(ui_TRAN_TEMP_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_TRAN_TEMP_CHART = lv_chart_create(ui_TRAN_TEMP);
    lv_obj_set_width(ui_TRAN_TEMP_CHART, 345);
    lv_obj_set_height(ui_TRAN_TEMP_CHART, 68);
    lv_obj_set_x(ui_TRAN_TEMP_CHART, 84);
    lv_obj_set_y(ui_TRAN_TEMP_CHART, -2);
    lv_obj_set_align(ui_TRAN_TEMP_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TRAN_TEMP_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_TRAN_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_TRAN_TEMP_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_TRAN_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_TRAN_TEMP_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_TRAN_TEMP_CHART, 24);
    lv_chart_set_range(ui_TRAN_TEMP_CHART, LV_CHART_AXIS_PRIMARY_Y, 80, 280);
    lv_chart_set_div_line_count(ui_TRAN_TEMP_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_TRAN_TEMP_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TRAN_TEMP_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_TRAN_TEMP_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TRAN_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_CHART_Xaxis = lv_scale_create(ui_TRAN_TEMP_CHART);
    lv_scale_set_mode(ui_TRAN_TEMP_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_TRAN_TEMP_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_TRAN_TEMP_CHART_Xaxis, false);
    ui_TRAN_TEMP_CHART_Yaxis1 = lv_scale_create(ui_TRAN_TEMP_CHART);
    lv_scale_set_mode(ui_TRAN_TEMP_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_TRAN_TEMP_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_TRAN_TEMP_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_TRAN_TEMP_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_TRAN_TEMP_CHART_Yaxis1,  80, 280);
    lv_scale_set_total_tick_count(ui_TRAN_TEMP_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_TRAN_TEMP_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_TRAN_TEMP_CHART_Yaxis1, false);
    ui_TRAN_TEMP_CHART_Yaxis2 = lv_scale_create(ui_TRAN_TEMP_CHART);
    lv_scale_set_mode(ui_TRAN_TEMP_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_TRAN_TEMP_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_TRAN_TEMP_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_TRAN_TEMP_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_TRAN_TEMP_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_TRAN_TEMP_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_TRAN_TEMP_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_TRAN_TEMP_CHART_Yaxis2, false);
    lv_chart_series_t * ui_TRAN_TEMP_CHART_series_1 = lv_chart_add_series(ui_TRAN_TEMP_CHART, lv_color_hex(0xEA871E),
                                                                          LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_TRAN_TEMP_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_TRAN_TEMP_CHART, ui_TRAN_TEMP_CHART_series_1, ui_TRAN_TEMP_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_TRAN_TEMP_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_TRAN_TEMP_Value_H = lv_label_create(ui_TRAN_TEMP);
    lv_obj_set_width(ui_TRAN_TEMP_Value_H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_Value_H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_Value_H, -5);
    lv_obj_set_y(ui_TRAN_TEMP_Value_H, -15);
    lv_obj_set_align(ui_TRAN_TEMP_Value_H, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TRAN_TEMP_Value_H, "0°F [H]");
    lv_obj_set_style_text_font(ui_TRAN_TEMP_Value_H, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_Value_C = lv_label_create(ui_TRAN_TEMP);
    lv_obj_set_width(ui_TRAN_TEMP_Value_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_Value_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_Value_C, -5);
    lv_obj_set_y(ui_TRAN_TEMP_Value_C, 14);
    lv_obj_set_align(ui_TRAN_TEMP_Value_C, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_TRAN_TEMP_Value_C, "0°F [C]");
    lv_obj_set_style_text_font(ui_TRAN_TEMP_Value_C, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TRAN_TEMP_VALUE_CRITICAL_Label = lv_label_create(ui_TRAN_TEMP);
    lv_obj_set_width(ui_TRAN_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TRAN_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TRAN_TEMP_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_TRAN_TEMP_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_TRAN_TEMP_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TRAN_TEMP_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_TRAN_TEMP_VALUE_CRITICAL_Label, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TRAN_TEMP_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_TRAN_TEMP_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TRAN_TEMP_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_STEER_TEMP);
    lv_obj_set_height(ui_STEER_TEMP, 68);
    lv_obj_set_width(ui_STEER_TEMP, lv_pct(105));
    lv_obj_set_x(ui_STEER_TEMP, 0);
    lv_obj_set_y(ui_STEER_TEMP, 252);
    lv_obj_set_align(ui_STEER_TEMP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_STEER_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_STEER_TEMP_Label = lv_label_create(ui_STEER_TEMP);
    lv_obj_set_width(ui_STEER_TEMP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_Label, 9);
    lv_obj_set_y(ui_STEER_TEMP_Label, 0);
    lv_obj_set_align(ui_STEER_TEMP_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_STEER_TEMP_Label, "STEER-TEMP");
    lv_obj_set_style_text_font(ui_STEER_TEMP_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_Image_1 = lv_image_create(ui_STEER_TEMP);
    lv_image_set_src(ui_STEER_TEMP_Image_1, &ui_img_837429808);
    lv_obj_set_width(ui_STEER_TEMP_Image_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_Image_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_Image_1, 218);
    lv_obj_set_y(ui_STEER_TEMP_Image_1, 11);
    lv_obj_set_align(ui_STEER_TEMP_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_STEER_TEMP_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_STEER_TEMP_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_STEER_TEMP_Image_1, 100);
    lv_obj_set_style_image_recolor(ui_STEER_TEMP_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_STEER_TEMP_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_Image_2 = lv_image_create(ui_STEER_TEMP);
    lv_image_set_src(ui_STEER_TEMP_Image_2, &ui_img_91236053);
    lv_obj_set_width(ui_STEER_TEMP_Image_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_Image_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_Image_2, 234);
    lv_obj_set_y(ui_STEER_TEMP_Image_2, -18);
    lv_obj_set_align(ui_STEER_TEMP_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_STEER_TEMP_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_STEER_TEMP_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_STEER_TEMP_Image_2, 125);
    lv_obj_set_style_image_recolor(ui_STEER_TEMP_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_STEER_TEMP_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_Bar = lv_bar_create(ui_STEER_TEMP);
    lv_bar_set_range(ui_STEER_TEMP_Bar, 60, 300);
    lv_obj_set_width(ui_STEER_TEMP_Bar, 345);
    lv_obj_set_height(ui_STEER_TEMP_Bar, 66);
    lv_obj_set_x(ui_STEER_TEMP_Bar, 84);
    lv_obj_set_y(ui_STEER_TEMP_Bar, -1);
    lv_obj_set_align(ui_STEER_TEMP_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_STEER_TEMP_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STEER_TEMP_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STEER_TEMP_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_STEER_TEMP_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_STEER_TEMP_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STEER_TEMP_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_STEER_TEMP_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_STEER_TEMP_Bar,
                                                                                                     lv_obj_get_style_pad_right(ui_STEER_TEMP_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_STEER_TEMP_CHART = lv_chart_create(ui_STEER_TEMP);
    lv_obj_set_width(ui_STEER_TEMP_CHART, 345);
    lv_obj_set_height(ui_STEER_TEMP_CHART, 68);
    lv_obj_set_x(ui_STEER_TEMP_CHART, 84);
    lv_obj_set_y(ui_STEER_TEMP_CHART, -2);
    lv_obj_set_align(ui_STEER_TEMP_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_STEER_TEMP_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_STEER_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_STEER_TEMP_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_STEER_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_STEER_TEMP_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_STEER_TEMP_CHART, 24);
    lv_chart_set_range(ui_STEER_TEMP_CHART, LV_CHART_AXIS_PRIMARY_Y, 60, 300);
    lv_chart_set_div_line_count(ui_STEER_TEMP_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_STEER_TEMP_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_STEER_TEMP_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_STEER_TEMP_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_STEER_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_CHART_Xaxis = lv_scale_create(ui_STEER_TEMP_CHART);
    lv_scale_set_mode(ui_STEER_TEMP_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_STEER_TEMP_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_STEER_TEMP_CHART_Xaxis, false);
    ui_STEER_TEMP_CHART_Yaxis1 = lv_scale_create(ui_STEER_TEMP_CHART);
    lv_scale_set_mode(ui_STEER_TEMP_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_STEER_TEMP_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_STEER_TEMP_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_STEER_TEMP_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_STEER_TEMP_CHART_Yaxis1,  60, 300);
    lv_scale_set_total_tick_count(ui_STEER_TEMP_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_STEER_TEMP_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_STEER_TEMP_CHART_Yaxis1, false);
    ui_STEER_TEMP_CHART_Yaxis2 = lv_scale_create(ui_STEER_TEMP_CHART);
    lv_scale_set_mode(ui_STEER_TEMP_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_STEER_TEMP_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_STEER_TEMP_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_STEER_TEMP_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_STEER_TEMP_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_STEER_TEMP_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_STEER_TEMP_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_STEER_TEMP_CHART_Yaxis2, false);
    lv_chart_series_t * ui_STEER_TEMP_CHART_series_1 = lv_chart_add_series(ui_STEER_TEMP_CHART, lv_color_hex(0xEA871E),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_STEER_TEMP_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_STEER_TEMP_CHART, ui_STEER_TEMP_CHART_series_1, ui_STEER_TEMP_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_STEER_TEMP_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_STEER_TEMP_Value_H = lv_label_create(ui_STEER_TEMP);
    lv_obj_set_width(ui_STEER_TEMP_Value_H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_Value_H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_Value_H, -5);
    lv_obj_set_y(ui_STEER_TEMP_Value_H, -15);
    lv_obj_set_align(ui_STEER_TEMP_Value_H, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_STEER_TEMP_Value_H, "0°F [H]");
    lv_obj_set_style_text_font(ui_STEER_TEMP_Value_H, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_Value_C = lv_label_create(ui_STEER_TEMP);
    lv_obj_set_width(ui_STEER_TEMP_Value_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_Value_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_Value_C, -5);
    lv_obj_set_y(ui_STEER_TEMP_Value_C, 14);
    lv_obj_set_align(ui_STEER_TEMP_Value_C, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_STEER_TEMP_Value_C, "0°F [C]");
    lv_obj_set_style_text_font(ui_STEER_TEMP_Value_C, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STEER_TEMP_VALUE_CRITICAL_Label = lv_label_create(ui_STEER_TEMP);
    lv_obj_set_width(ui_STEER_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STEER_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_STEER_TEMP_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_STEER_TEMP_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_STEER_TEMP_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_STEER_TEMP_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_STEER_TEMP_VALUE_CRITICAL_Label, lv_color_hex(0x960000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_STEER_TEMP_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_STEER_TEMP_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_STEER_TEMP_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_DIFF_TEMP);
    lv_obj_set_height(ui_DIFF_TEMP, 68);
    lv_obj_set_width(ui_DIFF_TEMP, lv_pct(105));
    lv_obj_set_x(ui_DIFF_TEMP, 0);
    lv_obj_set_y(ui_DIFF_TEMP, 320);
    lv_obj_set_align(ui_DIFF_TEMP, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_DIFF_TEMP, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DIFF_TEMP_Label = lv_label_create(ui_DIFF_TEMP);
    lv_obj_set_width(ui_DIFF_TEMP_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_Label, 9);
    lv_obj_set_y(ui_DIFF_TEMP_Label, 0);
    lv_obj_set_align(ui_DIFF_TEMP_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DIFF_TEMP_Label, "DIFF-TEMP");
    lv_obj_set_style_text_font(ui_DIFF_TEMP_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_Image_1 = lv_image_create(ui_DIFF_TEMP);
    lv_image_set_src(ui_DIFF_TEMP_Image_1, &ui_img_260142572);
    lv_obj_set_width(ui_DIFF_TEMP_Image_1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_Image_1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_Image_1, 218);
    lv_obj_set_y(ui_DIFF_TEMP_Image_1, 11);
    lv_obj_set_align(ui_DIFF_TEMP_Image_1, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DIFF_TEMP_Image_1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DIFF_TEMP_Image_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_DIFF_TEMP_Image_1, 125);
    lv_obj_set_style_image_recolor(ui_DIFF_TEMP_Image_1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_DIFF_TEMP_Image_1, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_Image_2 = lv_image_create(ui_DIFF_TEMP);
    lv_image_set_src(ui_DIFF_TEMP_Image_2, &ui_img_91236053);
    lv_obj_set_width(ui_DIFF_TEMP_Image_2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_Image_2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_Image_2, 234);
    lv_obj_set_y(ui_DIFF_TEMP_Image_2, -18);
    lv_obj_set_align(ui_DIFF_TEMP_Image_2, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_DIFF_TEMP_Image_2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DIFF_TEMP_Image_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_DIFF_TEMP_Image_2, 125);
    lv_obj_set_style_image_recolor(ui_DIFF_TEMP_Image_2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_DIFF_TEMP_Image_2, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_Bar = lv_bar_create(ui_DIFF_TEMP);
    lv_bar_set_range(ui_DIFF_TEMP_Bar, 60, 320);
    lv_obj_set_width(ui_DIFF_TEMP_Bar, 345);
    lv_obj_set_height(ui_DIFF_TEMP_Bar, 66);
    lv_obj_set_x(ui_DIFF_TEMP_Bar, 84);
    lv_obj_set_y(ui_DIFF_TEMP_Bar, -1);
    lv_obj_set_align(ui_DIFF_TEMP_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_DIFF_TEMP_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DIFF_TEMP_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DIFF_TEMP_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_DIFF_TEMP_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DIFF_TEMP_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DIFF_TEMP_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_DIFF_TEMP_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_DIFF_TEMP_Bar,
                                                                                                    lv_obj_get_style_pad_right(ui_DIFF_TEMP_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_DIFF_TEMP_CHART = lv_chart_create(ui_DIFF_TEMP);
    lv_obj_set_width(ui_DIFF_TEMP_CHART, 345);
    lv_obj_set_height(ui_DIFF_TEMP_CHART, 68);
    lv_obj_set_x(ui_DIFF_TEMP_CHART, 84);
    lv_obj_set_y(ui_DIFF_TEMP_CHART, -2);
    lv_obj_set_align(ui_DIFF_TEMP_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DIFF_TEMP_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_DIFF_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_DIFF_TEMP_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_DIFF_TEMP_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_DIFF_TEMP_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_DIFF_TEMP_CHART, 24);
    lv_chart_set_range(ui_DIFF_TEMP_CHART, LV_CHART_AXIS_PRIMARY_Y, 60, 320);
    lv_chart_set_div_line_count(ui_DIFF_TEMP_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_DIFF_TEMP_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DIFF_TEMP_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_DIFF_TEMP_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DIFF_TEMP_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_CHART_Xaxis = lv_scale_create(ui_DIFF_TEMP_CHART);
    lv_scale_set_mode(ui_DIFF_TEMP_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_DIFF_TEMP_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_DIFF_TEMP_CHART_Xaxis, false);
    ui_DIFF_TEMP_CHART_Yaxis1 = lv_scale_create(ui_DIFF_TEMP_CHART);
    lv_scale_set_mode(ui_DIFF_TEMP_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_DIFF_TEMP_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_DIFF_TEMP_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_DIFF_TEMP_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_DIFF_TEMP_CHART_Yaxis1,  60, 320);
    lv_scale_set_total_tick_count(ui_DIFF_TEMP_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_DIFF_TEMP_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_DIFF_TEMP_CHART_Yaxis1, false);
    ui_DIFF_TEMP_CHART_Yaxis2 = lv_scale_create(ui_DIFF_TEMP_CHART);
    lv_scale_set_mode(ui_DIFF_TEMP_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_DIFF_TEMP_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_DIFF_TEMP_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_DIFF_TEMP_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_DIFF_TEMP_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_DIFF_TEMP_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_DIFF_TEMP_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_DIFF_TEMP_CHART_Yaxis2, false);
    lv_chart_series_t * ui_DIFF_TEMP_CHART_series_1 = lv_chart_add_series(ui_DIFF_TEMP_CHART, lv_color_hex(0xEA871E),
                                                                          LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_DIFF_TEMP_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_DIFF_TEMP_CHART, ui_DIFF_TEMP_CHART_series_1, ui_DIFF_TEMP_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_DIFF_TEMP_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_DIFF_TEMP_Value_H = lv_label_create(ui_DIFF_TEMP);
    lv_obj_set_width(ui_DIFF_TEMP_Value_H, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_Value_H, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_Value_H, -5);
    lv_obj_set_y(ui_DIFF_TEMP_Value_H, -15);
    lv_obj_set_align(ui_DIFF_TEMP_Value_H, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DIFF_TEMP_Value_H, "0°F [H]");
    lv_obj_set_style_text_font(ui_DIFF_TEMP_Value_H, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_Value_C = lv_label_create(ui_DIFF_TEMP);
    lv_obj_set_width(ui_DIFF_TEMP_Value_C, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_Value_C, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_Value_C, -5);
    lv_obj_set_y(ui_DIFF_TEMP_Value_C, 14);
    lv_obj_set_align(ui_DIFF_TEMP_Value_C, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DIFF_TEMP_Value_C, "0°F [C]");
    lv_obj_set_style_text_font(ui_DIFF_TEMP_Value_C, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DIFF_TEMP_VALUE_CRITICAL_Label = lv_label_create(ui_DIFF_TEMP);
    lv_obj_set_width(ui_DIFF_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DIFF_TEMP_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DIFF_TEMP_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_DIFF_TEMP_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_DIFF_TEMP_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DIFF_TEMP_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_DIFF_TEMP_VALUE_CRITICAL_Label, lv_color_hex(0x960000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DIFF_TEMP_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_DIFF_TEMP_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DIFF_TEMP_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_TRUST = lv_obj_create(ui_MainPanel);
    lv_obj_remove_style_all(ui_FUEL_TRUST);
    lv_obj_set_height(ui_FUEL_TRUST, 68);
    lv_obj_set_width(ui_FUEL_TRUST, lv_pct(105));
    lv_obj_set_x(ui_FUEL_TRUST, 0);
    lv_obj_set_y(ui_FUEL_TRUST, 388);
    lv_obj_set_align(ui_FUEL_TRUST, LV_ALIGN_TOP_MID);
    lv_obj_remove_flag(ui_FUEL_TRUST, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_FUEL_TRUST_Label = lv_label_create(ui_FUEL_TRUST);
    lv_obj_set_width(ui_FUEL_TRUST_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_TRUST_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_TRUST_Label, 9);
    lv_obj_set_y(ui_FUEL_TRUST_Label, 0);
    lv_obj_set_align(ui_FUEL_TRUST_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FUEL_TRUST_Label, "FUEL-TRUST");
    lv_obj_set_style_text_font(ui_FUEL_TRUST_Label, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_TRUST_Image = lv_image_create(ui_FUEL_TRUST);
    lv_image_set_src(ui_FUEL_TRUST_Image, &ui_img_2038433484);
    lv_obj_set_width(ui_FUEL_TRUST_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_TRUST_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_TRUST_Image, 218);
    lv_obj_set_y(ui_FUEL_TRUST_Image, 1);
    lv_obj_set_align(ui_FUEL_TRUST_Image, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_FUEL_TRUST_Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_FUEL_TRUST_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_FUEL_TRUST_Image, 125);
    lv_obj_set_style_image_recolor(ui_FUEL_TRUST_Image, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_FUEL_TRUST_Image, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_TRUST_Bar = lv_bar_create(ui_FUEL_TRUST);
    lv_bar_set_range(ui_FUEL_TRUST_Bar, 5, 100);
    lv_obj_set_width(ui_FUEL_TRUST_Bar, 345);
    lv_obj_set_height(ui_FUEL_TRUST_Bar, 68);
    lv_obj_set_x(ui_FUEL_TRUST_Bar, 84);
    lv_obj_set_y(ui_FUEL_TRUST_Bar, 0);
    lv_obj_set_align(ui_FUEL_TRUST_Bar, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_FUEL_TRUST_Bar, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUEL_TRUST_Bar, lv_color_hex(0x32231E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUEL_TRUST_Bar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_radius(ui_FUEL_TRUST_Bar, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FUEL_TRUST_Bar, lv_color_hex(0xFF4500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUEL_TRUST_Bar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_FUEL_TRUST_Bar, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_FUEL_TRUST_Bar,
                                                                                                     lv_obj_get_style_pad_right(ui_FUEL_TRUST_Bar, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_FUEL_TRUST_CHART = lv_chart_create(ui_FUEL_TRUST);
    lv_obj_set_width(ui_FUEL_TRUST_CHART, 345);
    lv_obj_set_height(ui_FUEL_TRUST_CHART, 68);
    lv_obj_set_x(ui_FUEL_TRUST_CHART, 84);
    lv_obj_set_y(ui_FUEL_TRUST_CHART, 0);
    lv_obj_set_align(ui_FUEL_TRUST_CHART, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_FUEL_TRUST_CHART, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_FUEL_TRUST_CHART, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_FUEL_TRUST_CHART,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_FUEL_TRUST_CHART, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_FUEL_TRUST_CHART, LV_CHART_TYPE_BAR);
    lv_chart_set_point_count(ui_FUEL_TRUST_CHART, 24);
    lv_chart_set_range(ui_FUEL_TRUST_CHART, LV_CHART_AXIS_PRIMARY_Y, 5, 100);
    lv_chart_set_div_line_count(ui_FUEL_TRUST_CHART, 10, 10);
    lv_obj_set_style_bg_color(ui_FUEL_TRUST_CHART, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_FUEL_TRUST_CHART, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_FUEL_TRUST_CHART, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_FUEL_TRUST_CHART, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_TRUST_CHART_Xaxis = lv_scale_create(ui_FUEL_TRUST_CHART);
    lv_scale_set_mode(ui_FUEL_TRUST_CHART_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_align(ui_FUEL_TRUST_CHART_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Xaxis, 1, LV_PART_INDICATOR);
    lv_scale_set_label_show(ui_FUEL_TRUST_CHART_Xaxis, false);
    ui_FUEL_TRUST_CHART_Yaxis1 = lv_scale_create(ui_FUEL_TRUST_CHART);
    lv_scale_set_mode(ui_FUEL_TRUST_CHART_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_align(ui_FUEL_TRUST_CHART_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_FUEL_TRUST_CHART_Yaxis1, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_FUEL_TRUST_CHART_Yaxis1, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_range(ui_FUEL_TRUST_CHART_Yaxis1,  5, 100);
    lv_scale_set_total_tick_count(ui_FUEL_TRUST_CHART_Yaxis1, (0 > 0 ? 0 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_FUEL_TRUST_CHART_Yaxis1, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_FUEL_TRUST_CHART_Yaxis1, false);
    ui_FUEL_TRUST_CHART_Yaxis2 = lv_scale_create(ui_FUEL_TRUST_CHART);
    lv_scale_set_mode(ui_FUEL_TRUST_CHART_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_align(ui_FUEL_TRUST_CHART_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_FUEL_TRUST_CHART_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_FUEL_TRUST_CHART_Yaxis2, 0, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_FUEL_TRUST_CHART_Yaxis2, 0, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_FUEL_TRUST_CHART_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 2 + 1);
    lv_scale_set_major_tick_every(ui_FUEL_TRUST_CHART_Yaxis2, 2 >= 1 ? 2 : 1);
    lv_scale_set_label_show(ui_FUEL_TRUST_CHART_Yaxis2, false);
    lv_chart_series_t * ui_FUEL_TRUST_CHART_series_1 = lv_chart_add_series(ui_FUEL_TRUST_CHART, lv_color_hex(0xEA871E),
                                                                           LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_FUEL_TRUST_CHART_series_1_array[] = { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_FUEL_TRUST_CHART, ui_FUEL_TRUST_CHART_series_1, ui_FUEL_TRUST_CHART_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_width(ui_FUEL_TRUST_CHART, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_FUEL_TRUST_Value = lv_label_create(ui_FUEL_TRUST);
    lv_obj_set_width(ui_FUEL_TRUST_Value, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_TRUST_Value, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_TRUST_Value, -5);
    lv_obj_set_y(ui_FUEL_TRUST_Value, -1);
    lv_obj_set_align(ui_FUEL_TRUST_Value, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_FUEL_TRUST_Value, "0 %");
    lv_obj_set_style_text_font(ui_FUEL_TRUST_Value, &ui_font_OrbitronRegular26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FUEL_TRUST_VALUE_CRITICAL_Label = lv_label_create(ui_FUEL_TRUST);
    lv_obj_set_width(ui_FUEL_TRUST_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FUEL_TRUST_VALUE_CRITICAL_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FUEL_TRUST_VALUE_CRITICAL_Label, 313);
    lv_obj_set_y(ui_FUEL_TRUST_VALUE_CRITICAL_Label, 0);
    lv_obj_set_align(ui_FUEL_TRUST_VALUE_CRITICAL_Label, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FUEL_TRUST_VALUE_CRITICAL_Label, "VALUE CRITICAL");
    lv_obj_set_style_text_color(ui_FUEL_TRUST_VALUE_CRITICAL_Label, lv_color_hex(0x960000),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FUEL_TRUST_VALUE_CRITICAL_Label, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_FUEL_TRUST_VALUE_CRITICAL_Label, LV_TEXT_DECOR_UNDERLINE,
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FUEL_TRUST_VALUE_CRITICAL_Label, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Horizontal_Separators = NULL;
    ui_Horizontal_Separators1 = NULL;
    ui_Horizontal_Separators2 = NULL;
    ui_Horizontal_Separators3 = NULL;
    ui_Horizontal_Separators4 = NULL;
    ui_Horizontal_Separators5 = NULL;
    ui_Horizontal_Separators6 = NULL;
    ui_Vertival_Separators = NULL;
    ui_Vertival_Separators1 = NULL;
    ui_Vertival_Separators2 = NULL;
    ui_Vertival_Separators3 = NULL;
    ui_MainPanel = NULL;
    ui_OIL_PRESS = NULL;
    ui_OIL_PRESS_Label = NULL;
    ui_OIL_PRESS_Image_1 = NULL;
    ui_OIL_PRESS_Image_2 = NULL;
    ui_OIL_PRESS_Bar = NULL;
    ui_OIL_PRESS_CHART = NULL;
    ui_OIL_PRESS_Value = NULL;
    ui_OIL_PRESS_VALUE_CRITICAL_Label = NULL;
    ui_OIL_TEMP = NULL;
    ui_OIL_TEMP_Label = NULL;
    ui_OIL_TEMP_Image_1 = NULL;
    ui_OIL_TEMP_Image_2 = NULL;
    ui_OIL_TEMP_Bar = NULL;
    ui_OIL_TEMP_CHART = NULL;
    ui_OIL_TEMP_Value_P = NULL;
    ui_OIL_TEMP_Value_C = NULL;
    ui_OIL_TEMP_VALUE_CRITICAL_Label = NULL;
    ui_W_TEMP = NULL;
    ui_W_TEMP_Label = NULL;
    ui_W_TEMP_Image_1 = NULL;
    ui_W_TEMP_Image_2 = NULL;
    ui_W_TEMP_Bar = NULL;
    ui_W_TEMP_CHART = NULL;
    ui_W_TEMP_Value_H = NULL;
    ui_W_TEMP_Value_C = NULL;
    ui_W_TEMP_VALUE_CRITICAL_Label = NULL;
    ui_TRAN_TEMP = NULL;
    ui_TRAN_TEMP_Label = NULL;
    ui_TRAN_TEMP_Image_1 = NULL;
    ui_TRAN_TEMP_Image_2 = NULL;
    ui_TRAN_TEMP_Bar = NULL;
    ui_TRAN_TEMP_CHART = NULL;
    ui_TRAN_TEMP_Value_H = NULL;
    ui_TRAN_TEMP_Value_C = NULL;
    ui_TRAN_TEMP_VALUE_CRITICAL_Label = NULL;
    ui_STEER_TEMP = NULL;
    ui_STEER_TEMP_Label = NULL;
    ui_STEER_TEMP_Image_1 = NULL;
    ui_STEER_TEMP_Image_2 = NULL;
    ui_STEER_TEMP_Bar = NULL;
    ui_STEER_TEMP_CHART = NULL;
    ui_STEER_TEMP_Value_H = NULL;
    ui_STEER_TEMP_Value_C = NULL;
    ui_STEER_TEMP_VALUE_CRITICAL_Label = NULL;
    ui_DIFF_TEMP = NULL;
    ui_DIFF_TEMP_Label = NULL;
    ui_DIFF_TEMP_Image_1 = NULL;
    ui_DIFF_TEMP_Image_2 = NULL;
    ui_DIFF_TEMP_Bar = NULL;
    ui_DIFF_TEMP_CHART = NULL;
    ui_DIFF_TEMP_Value_H = NULL;
    ui_DIFF_TEMP_Value_C = NULL;
    ui_DIFF_TEMP_VALUE_CRITICAL_Label = NULL;
    ui_FUEL_TRUST = NULL;
    ui_FUEL_TRUST_Label = NULL;
    ui_FUEL_TRUST_Image = NULL;
    ui_FUEL_TRUST_Bar = NULL;
    ui_FUEL_TRUST_CHART = NULL;
    ui_FUEL_TRUST_Value = NULL;
    ui_FUEL_TRUST_VALUE_CRITICAL_Label = NULL;

}
